### ISSUE TITLE
Error when summarizing year

### ISSUE THREAD

**Issue by simistef** [steven-murray/beet-summarize#11]
I get an error on the year tag summarisation. Apparently it works ok with Genre tag. Would this have to do with the fact that some of year tags are empty ?

```
root@linuxserver-beets1:/# beet summarize -g year -R         
                    
Traceback (most recent call last):                                               
  File "/usr/bin/beet", line 33, in <module>                                     
    sys.exit(load_entry_point('beets==1.6.0', 'console_scripts', 'beet')())      
  File "/usr/lib/python3.9/site-packages/beets/ui/__init__.py", line 1285, in mai
n                                                                                
    _raw_main(args)                                                              
  File "/usr/lib/python3.9/site-packages/beets/ui/__init__.py", line 1272, in _ra
w_main                                                                           
    subcommand.func(lib, suboptions, subargs)                                    
  File "/usr/lib/python3.9/site-packages/beetsplug/summarize.py", line 235, in su
mmarize                                                                          
    show_summary(lib, decargs(args), opts.group_by, opts.stats, not opts.not_reve
rse)                                                                             
  File "/usr/lib/python3.9/site-packages/beetsplug/summarize.py", line 230, in sh
ow_summary                                                                       
    print_results(stat_dct, category, sort_stat, reverse)                        
  File "/usr/lib/python3.9/site-packages/beetsplug/summarize.py", line 210, in pr
int_results                                                                      
    print_dct_as_table(keys, dcts, cat_name)                                     
  File "/usr/lib/python3.9/site-packages/beetsplug/summarize.py", line 197, in pr
int_dct_as_table                                                                 
    col_size = [max(map(len, col)) for col in zip(*table)]                       
  File "/usr/lib/python3.9/site-packages/beetsplug/summarize.py", line 197, in <l
istcomp>                                                                         
    col_size = [max(map(len, col)) for col in zip(*table)]                       
TypeError: object of type 'int' has no len(
```

**Comment by steven-murray** [comment]
@simistef thanks for the issue. Yes that seems a likely cause. If I get a minute to look into it I'll try fix it.

**Comment by steven-murray** [comment]
@simistef can you confirm that main branch now works?

**Comment by simistef** [comment]
I tried to reinstall, but I got into this error now:

`root@linuxserver-beets1:/# pip install git+git://github.com/steven-murray/beet-su
mmarize.git                                                                      
WARNING: The directory '/config/.cache/pip' or its parent directory is not owned 
or is not writable by the current user. The cache has been disabled. Check the pe
rmissions and owner of that directory. If executing pip with sudo, you should use
 sudo's -H flag.                                                                 
Collecting git+git://github.com/steven-murray/beet-summarize.git                 
  Cloning git://github.com/steven-murray/beet-summarize.git to /tmp/pip-req-build
-qh86uc77                                                                        
  Running command git clone --filter=blob:none --quiet git://github.com/steven-mu
rray/beet-summarize.git /tmp/pip-req-build-qh86uc77                              
                                                                                 
  fatal: unable to connect to github.com:                                        
  github.com[0: 140.82.121.3]: errno=Operation timed out                         
                                                                                 
  error: subprocess-exited-with-error                                            
                                                                                 
  × git clone --filter=blob:none --quiet git://github.com/steven-murray/beet-summ
arize.git /tmp/pip-req-build-qh86uc77 did not run successfully.                  
  │ exit code: 128                                                               
  ╰─> See above for output.                                                      
                                                                                 
  note: This error originates from a subprocess, and is likely not a problem with
 pip.                                                                            
error: subprocess-exited-with-error              
root@linuxserver-beets1:/# pip install git+git://github.com/steven-murray/beet-su
mmarize.git                                                                      
WARNING: The directory '/config/.cache/pip' or its parent directory is not owned 
or is not writable by the current user. The cache has been disabled. Check the pe
rmissions and owner of that directory. If executing pip with sudo, you should use
 sudo's -H flag.                                                                 
Collecting git+git://github.com/steven-murray/beet-summarize.git                 
  Cloning git://github.com/steven-murray/beet-summarize.git to /tmp/pip-req-build
-qh86uc77                                                                        
  Running command git clone --filter=blob:none --quiet git://github.com/steven-mu
rray/beet-summarize.git /tmp/pip-req-build-qh86uc77                              
                                                                                 
  fatal: unable to connect to github.com:                                        
  github.com[0: 140.82.121.3]: errno=Operation timed out                         
                                                                                 
  error: subprocess-exited-with-error                                            
                                                                                 
  × git clone --filter=blob:none --quiet git://github.com/steven-murray/beet-summ
arize.git /tmp/pip-req-build-qh86uc77 did not run successfully.                  
  │ exit code: 128                                                               
  ╰─> See above for output.                                                      
                                                                                 
  note: This error originates from a subprocess, and is likely not a problem with
 pip.                                                                            
error: subprocess-exited-with-error              `

**Comment by steven-murray** [comment]
Please note you need to install with `pip install git+https://....` not `pip install git+git://...`

**Comment by simistef** [comment]
it worked now. thank you very much !
